services:
  ankorbridge-server:
    container_name: ankorbridge-server
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - ankorbridge-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  ankorbridge-database:
    container_name: ankorbridge-database
    image: mysql:8
    restart: always
    networks:
      - ankorbridge-network
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ankorbridge-database-data:/var/lib/mysql
    env_file:
      - .env

  ankorbridge-jaeger:
    container_name: ankorbridge-jaeger
    image: jaegertracing/all-in-one
    networks:
      - ankorbridge-network
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  ankorbridge-database-data:
    driver: local

networks:
  ankorbridge-network:
    driver: bridge
